-- =============================================
-- User-owned app tables with ownership-based RLS
-- Apply after the profiles migration.
-- =============================================

-- All user-owned app tables (clients, time_entries, payments,
-- settings, subscriptions) have been removed for MVP simplicity.
-- The profiles table in migration 001 handles auth and onboarding.
-- When new user-owned tables are needed, add them here with
-- the standard RLS pattern:
--
-- create table if not exists public.<table> (
--   id uuid primary key default gen_random_uuid(),
--   user_id uuid not null references auth.users(id) on delete cascade,
--   ...
--   created_at timestamptz not null default now(),
--   updated_at timestamptz not null default now()
-- );
--
-- alter table public.<table> enable row level security;
-- grant select, insert, update, delete on public.<table> to anon, authenticated, service_role;
--
-- create policy "Users manage own <table>"
--   on public.<table>
--   for all
--   to authenticated
--   using (auth.uid() = user_id)
--   with check (auth.uid() = user_id);
